### ISSUE TITLE
[Docs] Update docs to provide better getting started and tracing explanations

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#1606]
On the [Tempo community Slack channel](https://grafana.slack.com/archives/C01D981PEE5/p1659017757315569?thread_ts=1659015048.642619&cid=C01D981PEE5), Yatekii noted several issues with the Tempo docs (and Grafana docs in general):

>But most of the issues arose from the entire setup and little clarity how the entire tracing works. Also in my backend setup (Rust). I guess if I knew this before, Tempo would have been easy to setup. But docs are really not straightforward. Especially on grafana. Some parts mentioning the ini format and then other parts using yaml format. How you can set the config file location is burried in the docs somewhere. The installation section focuses on specific tools instead of just being "hey, run this docker container and map this file". You can get that info from the docker-compose, which is nice! but there you have additional services which then are not obvious to me whether I need them or not. Take Loki. The docker-compose also contains promtail, but if I understand correct that is not used at all. Nobody tells me this. All the educational videos have so many holes in the story, just assuming you know 80% already.

This issue will work to address these issues: 
* How does tracing work in the backend and backend setup? Esp. with Rust. 
* How does sampling work? -- We need to explain basic concepts better.
* Clarify pages that use the INI vs the YAML files. 
* Clarify (make it easier to find) how you set up the config file location
* The Install section is focused on tools instead of just having a quick start "Run this docker-compse" 
** Add pointers to which options are required, recommended, optional. (Maybe an opinionated installation instruction would address this.) 

```[tasklist]
### Tasks
- [x] Add a definition of tracing, traces, transactions.
- [ ] Add an explanation for how tracing works in the back end and backend set up? Especially with Rust.
- [ ] How does sampling work? (see tail samplilng doc in Grafana Agent doc) 
- [ ] Clarify pages that use the INI vs the YAML files
- [ ] Clarify how to set up the config file location
- [ ] Add a docker-complose example to the install section
- [x] Why is tracing important? What does a trace look like as data and how is it stored?
- [ ] What are the complexity downsides of having tracing? In what case is this complexity worth it? In what times is tracing not worth it?
```

**Comment by knylander-grafana** [comment]
@mapno and @electron0zero This issue could use some help with explaining basic concepts like tracing, sampling, etc.

**Comment by knylander-grafana** [comment]
Related ticket: https://github.com/grafana/tempo/issues/1721

**Comment by GrafanaWriter** [comment]
I believe this has been fixed.
