### ISSUE TITLE
[DOC] Tempo 2.4 release notes

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#3402]
Create [release notes](https://grafana.com/docs/tempo/latest/release-notes/v2-3/) for Tempo 2.4. 

Highlighted features: 
* TraceQL metrics
* Parquetv3 as default
* Cache refactor
* Polling improvements 
* Corrected an issue causing Trace too large errors

```[tasklist]
### Tasks
- [x] Review the changelog for the latest list of changes to include
- [x] Group changes by content and highlighted features
- [x] Write summaries for the major features
- [x] Review all documentation related to updates and features for the release
- [x] Link to updated and new docs for updates and features to the release notes
- [x] Update the "Upgrade Tempo" page with any breaking changes and configurations
- [x] Preview content to check for errors
- [x] Publish with the release
```
