### ISSUE TITLE
Tempo Query Frontend Refactor

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3413]
The query frontend code has been pushed to its absolute limits. We need a refactor for improved code clarity, performance, enable streaming on all endpoints and pave the way for more advanced features demanded by TraceQL metrics.

The first PR has been opened and will address the first two tasks when merged: https://github.com/grafana/tempo/pull/3400

**Tasks**

- [x] Build tools to construct asynchronous pipelines
- [x] Migrate search to the new pipelines
- [x] Migrate tag endpoints to the new pipelines
- [x] Migrate trace id endpoints to the new pipelines. (remain synchronous but use new patterns)
- [x] Migrate metrics summary api to the new pipelines. (remain synchronous but use new patterns)
- [ ] Build and use structures to support deterministic search
- [x] Build experimental metrics streaming API

**Stretch**

- [x] Measure/Improve job throughput. At least don't slow things down.
- [ ] Issue multiple ingester search queries instead of one.

**Existing/Relevant Issues**

- https://github.com/grafana/tempo/issues/1392
- https://github.com/grafana/tempo/issues/3366
- Deterministic search
  - https://github.com/grafana/tempo/issues/2659
  - https://github.com/grafana/tempo/issues/3109

**Comment by joe-elliott** [comment]
We discovered some goroutine leaks in the existing implementation. Fix here:

https://github.com/grafana/tempo/pull/3495

**Comment by joe-elliott** [comment]
Tags streaming:

https://github.com/grafana/tempo/pull/3460

**Comment by joe-elliott** [comment]
Multiple ingester queries are being handled here:

https://github.com/grafana/tempo/pull/3574
