### ISSUE TITLE
[DOC] Update Tempo docs for Agent > Alloy

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#3648]
Review the Tempo documentation to use Alloy instead of Agent. 

Reference: https://github.com/grafana/pyroscope/pull/3272
Related: https://github.com/grafana/tempo-squad/issues/440

```[tasklist]
### Tasks
- [x] Review existing documentation to see which pages reference Agent, include the set up and any config pages.
- [x] Are example configs in static or flow (river)?
- [x] Update set up pages in Tempo docs
- [x] Update other pages
- [x] Update Alloy docs to include traces for Migration from Staic
- [x] Update Alloy docs to include traces for Migrate from Flow
- [x] Verify with the Alloy writer
```

**Comment by clayton-cornell** [comment]
[list.txt](https://github.com/grafana/tempo/files/15338316/list.txt)

**Comment by knylander-grafana** [comment]
Update Agent >Alloy  for Helm chart doc: https://github.com/grafana/tempo-squad/issues/440
